// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBihw1FmHpjrozn7zZnXW0TKkQSytEJJCM',
    appId: '1:326757512073:web:1d6af8ca7973c5dde86758',
    messagingSenderId: '326757512073',
    projectId: 'meetup-web-app-b6a17',
    authDomain: 'meetup-web-app-b6a17.firebaseapp.com',
    storageBucket: 'meetup-web-app-b6a17.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2VI1Qy_PQpIYZ7YlVVgTA1VE-lB-Zhcc',
    appId: '1:326757512073:ios:bb586996a6fecac5e86758',
    messagingSenderId: '326757512073',
    projectId: 'meetup-web-app-b6a17',
    storageBucket: 'meetup-web-app-b6a17.appspot.com',
    iosClientId: '326757512073-qq4qv3f9hr3h8406bmavonmb5f7sei8c.apps.googleusercontent.com',
    iosBundleId: 'co.enspyr.meetupWebApp',
  );
}
